import type { VocabWord } from "@/store/listsStore";

export interface PredefinedList {
  id: string;
  name: string;
  topic: string;
  topicCategory: string;
  description: string;
  listLanguage: string;
  words: Omit<VocabWord, "status" | "timesCorrect" | "timesWrong">[];
}

export type ListCategory =
  | "all"
  | "travel"
  | "business"
  | "technology"
  | "daily_life"
  | "academic";

export const LIST_CATEGORIES: { key: ListCategory; labelKey: string }[] = [
  { key: "all", labelKey: "explore.category.all" },
  { key: "travel", labelKey: "explore.category.travel" },
  { key: "business", labelKey: "explore.category.business" },
  { key: "technology", labelKey: "explore.category.technology" },
  { key: "daily_life", labelKey: "explore.category.dailyLife" },
  { key: "academic", labelKey: "explore.category.academic" },
];

export const PREDEFINED_LISTS_EN: PredefinedList[] = [
  {
    id: "pre-en-travel-airport",
    name: "Airport Essentials",
    topic: "Airport & Flying",
    topicCategory: "travel",
    description: "Essential vocabulary for navigating airports and flying.",
    listLanguage: "English",
    words: [
      {
        id: "w1",
        term: "Boarding pass",
        translation: "Biniş kartı",
        example: "Please have your boarding pass ready.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "w2",
        term: "Gate",
        translation: "Kapı",
        example: "Your flight departs from gate B12.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "w3",
        term: "Luggage",
        translation: "Bagaj",
        example: "Please collect your luggage from carousel 3.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "w4",
        term: "Departure",
        translation: "Kalkış",
        example: "The departure is scheduled for 3 PM.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "w5",
        term: "Customs",
        translation: "Gümrük",
        example: "You need to go through customs after landing.",
        difficulty: "intermediate",
        partOfSpeech: "noun",
      },
      {
        id: "w6",
        term: "Turbulence",
        translation: "Türbülans",
        example: "We may experience some turbulence during the flight.",
        difficulty: "intermediate",
        partOfSpeech: "noun",
      },
      {
        id: "w7",
        term: "Layover",
        translation: "Aktarma",
        example: "We have a two-hour layover in Istanbul.",
        difficulty: "intermediate",
        partOfSpeech: "noun",
      },
      {
        id: "w8",
        term: "Aisle seat",
        translation: "Koridor tarafı koltuk",
        example: "I prefer an aisle seat for long flights.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "w9",
        term: "Check-in",
        translation: "Giriş işlemi",
        example: "Online check-in opens 24 hours before departure.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "w10",
        term: "Runway",
        translation: "Pist",
        example: "The plane is taxiing to the runway.",
        difficulty: "intermediate",
        partOfSpeech: "noun",
      },
    ],
  },
  {
    id: "pre-en-business-meeting",
    name: "Business Meeting",
    topic: "Business & Meetings",
    topicCategory: "business",
    description: "Key vocabulary for professional meetings and presentations.",
    listLanguage: "English",
    words: [
      {
        id: "w11",
        term: "Agenda",
        translation: "Gündem",
        example: "Let's review the agenda for today's meeting.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "w12",
        term: "Deadline",
        translation: "Son tarih",
        example: "The project deadline is next Friday.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "w13",
        term: "Stakeholder",
        translation: "Paydaş",
        example: "We need approval from all stakeholders.",
        difficulty: "intermediate",
        partOfSpeech: "noun",
      },
      {
        id: "w14",
        term: "Revenue",
        translation: "Gelir",
        example: "Our revenue increased by 15% this quarter.",
        difficulty: "intermediate",
        partOfSpeech: "noun",
      },
      {
        id: "w15",
        term: "Benchmark",
        translation: "Kıyaslama",
        example: "We use industry benchmarks to measure performance.",
        difficulty: "advanced",
        partOfSpeech: "noun",
      },
      {
        id: "w16",
        term: "Delegate",
        translation: "Yetki vermek",
        example: "You should delegate tasks to your team.",
        difficulty: "intermediate",
        partOfSpeech: "verb",
      },
      {
        id: "w17",
        term: "Proposal",
        translation: "Teklif",
        example: "The client accepted our proposal.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "w18",
        term: "Negotiate",
        translation: "Müzakere etmek",
        example: "We need to negotiate better terms.",
        difficulty: "intermediate",
        partOfSpeech: "verb",
      },
      {
        id: "w19",
        term: "Quarterly",
        translation: "Üç aylık",
        example: "We prepare quarterly financial reports.",
        difficulty: "intermediate",
        partOfSpeech: "adjective",
      },
      {
        id: "w20",
        term: "ROI",
        translation: "Yatırım getirisi",
        example: "The ROI on this project exceeded expectations.",
        difficulty: "advanced",
        partOfSpeech: "noun",
      },
    ],
  },
  {
    id: "pre-en-tech-programming",
    name: "Programming Basics",
    topic: "Software Development",
    topicCategory: "technology",
    description: "Common programming terminology for beginners.",
    listLanguage: "English",
    words: [
      {
        id: "w21",
        term: "Variable",
        translation: "Değişken",
        example: "Declare a variable to store the user's name.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "w22",
        term: "Function",
        translation: "Fonksiyon",
        example: "This function calculates the total price.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "w23",
        term: "Debug",
        translation: "Hata ayıklamak",
        example: "I spent two hours debugging this issue.",
        difficulty: "intermediate",
        partOfSpeech: "verb",
      },
      {
        id: "w24",
        term: "Repository",
        translation: "Depo",
        example: "Push your changes to the repository.",
        difficulty: "intermediate",
        partOfSpeech: "noun",
      },
      {
        id: "w25",
        term: "API",
        translation: "Uygulama programlama arayüzü",
        example: "The API returns data in JSON format.",
        difficulty: "intermediate",
        partOfSpeech: "noun",
      },
      {
        id: "w26",
        term: "Iterate",
        translation: "Yinelemek",
        example: "We iterate over the array to process each item.",
        difficulty: "intermediate",
        partOfSpeech: "verb",
      },
      {
        id: "w27",
        term: "Deploy",
        translation: "Dağıtmak",
        example: "We deploy the application to production every Friday.",
        difficulty: "intermediate",
        partOfSpeech: "verb",
      },
      {
        id: "w28",
        term: "Framework",
        translation: "Çerçeve",
        example: "React is a popular JavaScript framework.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "w29",
        term: "Algorithm",
        translation: "Algoritma",
        example: "This sorting algorithm has O(n log n) complexity.",
        difficulty: "advanced",
        partOfSpeech: "noun",
      },
      {
        id: "w30",
        term: "Middleware",
        translation: "Ara yazılım",
        example: "Add authentication middleware to protect routes.",
        difficulty: "advanced",
        partOfSpeech: "noun",
      },
    ],
  },
  {
    id: "pre-en-daily-kitchen",
    name: "In the Kitchen",
    topic: "Kitchen & Cooking",
    topicCategory: "daily_life",
    description: "Everyday vocabulary for cooking and kitchen items.",
    listLanguage: "English",
    words: [
      {
        id: "w31",
        term: "Whisk",
        translation: "Çırpıcı",
        example: "Use a whisk to mix the eggs.",
        difficulty: "intermediate",
        partOfSpeech: "noun",
      },
      {
        id: "w32",
        term: "Chop",
        translation: "Doğramak",
        example: "Chop the onions into small pieces.",
        difficulty: "beginner",
        partOfSpeech: "verb",
      },
      {
        id: "w33",
        term: "Simmer",
        translation: "Hafif ateşte pişirmek",
        example: "Let the sauce simmer for 20 minutes.",
        difficulty: "intermediate",
        partOfSpeech: "verb",
      },
      {
        id: "w34",
        term: "Spatula",
        translation: "Spatula",
        example: "Flip the pancake with a spatula.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "w35",
        term: "Marinate",
        translation: "Marine etmek",
        example: "Marinate the chicken for at least two hours.",
        difficulty: "intermediate",
        partOfSpeech: "verb",
      },
      {
        id: "w36",
        term: "Preheat",
        translation: "Önceden ısıtmak",
        example: "Preheat the oven to 180 degrees.",
        difficulty: "beginner",
        partOfSpeech: "verb",
      },
      {
        id: "w37",
        term: "Strain",
        translation: "Süzmek",
        example: "Strain the pasta when it's al dente.",
        difficulty: "intermediate",
        partOfSpeech: "verb",
      },
      {
        id: "w38",
        term: "Garnish",
        translation: "Süslemek",
        example: "Garnish the plate with fresh herbs.",
        difficulty: "intermediate",
        partOfSpeech: "verb",
      },
      {
        id: "w39",
        term: "Colander",
        translation: "Süzgeç",
        example: "Drain the vegetables in a colander.",
        difficulty: "intermediate",
        partOfSpeech: "noun",
      },
      {
        id: "w40",
        term: "Dice",
        translation: "Küp küp doğramak",
        example: "Dice the tomatoes for the salsa.",
        difficulty: "beginner",
        partOfSpeech: "verb",
      },
    ],
  },
  {
    id: "pre-en-academic-research",
    name: "Academic Research",
    topic: "Academic Writing",
    topicCategory: "academic",
    description: "Essential vocabulary for academic papers and research.",
    listLanguage: "English",
    words: [
      {
        id: "w41",
        term: "Hypothesis",
        translation: "Hipotez",
        example: "Our hypothesis was supported by the data.",
        difficulty: "intermediate",
        partOfSpeech: "noun",
      },
      {
        id: "w42",
        term: "Citation",
        translation: "Alıntı",
        example: "Include a citation for every source you reference.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "w43",
        term: "Methodology",
        translation: "Metodoloji",
        example:
          "The methodology section describes how the study was conducted.",
        difficulty: "intermediate",
        partOfSpeech: "noun",
      },
      {
        id: "w44",
        term: "Abstract",
        translation: "Özet",
        example: "The abstract summarizes the key findings.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "w45",
        term: "Peer review",
        translation: "Hakemli değerlendirme",
        example: "The paper underwent rigorous peer review.",
        difficulty: "advanced",
        partOfSpeech: "noun",
      },
      {
        id: "w46",
        term: "Empirical",
        translation: "Deneysel",
        example: "We provide empirical evidence for our claims.",
        difficulty: "advanced",
        partOfSpeech: "adjective",
      },
      {
        id: "w47",
        term: "Correlation",
        translation: "Korelasyon",
        example: "There is a strong correlation between the two variables.",
        difficulty: "intermediate",
        partOfSpeech: "noun",
      },
      {
        id: "w48",
        term: "Thesis",
        translation: "Tez",
        example: "She defended her thesis last month.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "w49",
        term: "Plagiarism",
        translation: "İntihal",
        example: "Plagiarism is a serious academic offense.",
        difficulty: "intermediate",
        partOfSpeech: "noun",
      },
      {
        id: "w50",
        term: "Quantitative",
        translation: "Nicel",
        example: "We used quantitative methods to analyze the data.",
        difficulty: "advanced",
        partOfSpeech: "adjective",
      },
    ],
  },
];

export const PREDEFINED_LISTS_TR: PredefinedList[] = [
  {
    id: "pre-tr-travel-hotel",
    name: "Otel & Konaklama",
    topic: "Otel & Konaklama",
    topicCategory: "travel",
    description: "Otelde ve konaklamada kullanılan temel kelimeler.",
    listLanguage: "Turkish",
    words: [
      {
        id: "wt1",
        term: "Reservation",
        translation: "Rezervasyon",
        example: "I have a reservation under my name.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "wt2",
        term: "Check out",
        translation: "Çıkış yapmak",
        example: "Check out time is at noon.",
        difficulty: "beginner",
        partOfSpeech: "verb",
      },
      {
        id: "wt3",
        term: "Room service",
        translation: "Oda servisi",
        example: "You can order room service until midnight.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "wt4",
        term: "Concierge",
        translation: "Danışma",
        example: "Ask the concierge for restaurant recommendations.",
        difficulty: "intermediate",
        partOfSpeech: "noun",
      },
      {
        id: "wt5",
        term: "Amenities",
        translation: "Olanaklar",
        example: "The hotel offers excellent amenities.",
        difficulty: "intermediate",
        partOfSpeech: "noun",
      },
      {
        id: "wt6",
        term: "Vacancy",
        translation: "Boş oda",
        example: "Do you have any vacancies for tonight?",
        difficulty: "intermediate",
        partOfSpeech: "noun",
      },
      {
        id: "wt7",
        term: "Bellboy",
        translation: "Otel görevlisi",
        example: "The bellboy helped carry our luggage.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "wt8",
        term: "Complimentary",
        translation: "Ücretsiz",
        example: "The hotel offers complimentary breakfast.",
        difficulty: "intermediate",
        partOfSpeech: "adjective",
      },
      {
        id: "wt9",
        term: "Suite",
        translation: "Süit",
        example: "We upgraded to a suite for our anniversary.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "wt10",
        term: "Housekeeping",
        translation: "Kat hizmeti",
        example: "Please contact housekeeping for extra towels.",
        difficulty: "intermediate",
        partOfSpeech: "noun",
      },
    ],
  },
  {
    id: "pre-tr-business-email",
    name: "İş E-postaları",
    topic: "İş Yazışmaları",
    topicCategory: "business",
    description: "İş e-postalarında sıkça kullanılan İngilizce ifadeler.",
    listLanguage: "Turkish",
    words: [
      {
        id: "wt11",
        term: "Attachment",
        translation: "Ek dosya",
        example: "Please find the report in the attachment.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "wt12",
        term: "Regards",
        translation: "Saygılarımla",
        example: "Best regards, John Smith.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "wt13",
        term: "Follow up",
        translation: "Takip etmek",
        example: "I am writing to follow up on our conversation.",
        difficulty: "intermediate",
        partOfSpeech: "verb",
      },
      {
        id: "wt14",
        term: "Hereby",
        translation: "Bu vesileyle",
        example: "I hereby confirm the meeting schedule.",
        difficulty: "advanced",
        partOfSpeech: "adverb",
      },
      {
        id: "wt15",
        term: "Recipient",
        translation: "Alıcı",
        example: "Make sure all recipients are included.",
        difficulty: "intermediate",
        partOfSpeech: "noun",
      },
      {
        id: "wt16",
        term: "Inquire",
        translation: "Sormak",
        example: "I am writing to inquire about availability.",
        difficulty: "intermediate",
        partOfSpeech: "verb",
      },
      {
        id: "wt17",
        term: "Acknowledge",
        translation: "Onaylamak",
        example: "Please acknowledge receipt of this email.",
        difficulty: "intermediate",
        partOfSpeech: "verb",
      },
      {
        id: "wt18",
        term: "Cc",
        translation: "Bilgi için",
        example: "I have Cc'd your manager on this email.",
        difficulty: "beginner",
        partOfSpeech: "verb",
      },
      {
        id: "wt19",
        term: "Priority",
        translation: "Öncelik",
        example: "This is a high priority request.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "wt20",
        term: "Apologies",
        translation: "Özür dilerim",
        example: "Apologies for the delayed response.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
    ],
  },
  {
    id: "pre-tr-tech-ai",
    name: "Yapay Zeka Terimleri",
    topic: "Yapay Zeka",
    topicCategory: "technology",
    description: "Yapay zeka ve makine öğrenmesi alanındaki temel terimler.",
    listLanguage: "Turkish",
    words: [
      {
        id: "wt21",
        term: "Neural network",
        translation: "Sinir ağı",
        example: "The neural network was trained on millions of images.",
        difficulty: "advanced",
        partOfSpeech: "noun",
      },
      {
        id: "wt22",
        term: "Dataset",
        translation: "Veri seti",
        example: "We need a larger dataset for better accuracy.",
        difficulty: "intermediate",
        partOfSpeech: "noun",
      },
      {
        id: "wt23",
        term: "Prediction",
        translation: "Tahmin",
        example: "The model's prediction was 95% accurate.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "wt24",
        term: "Training",
        translation: "Eğitim",
        example: "Model training took several hours.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "wt25",
        term: "Bias",
        translation: "Önyargı",
        example: "We must address bias in our training data.",
        difficulty: "intermediate",
        partOfSpeech: "noun",
      },
      {
        id: "wt26",
        term: "Classification",
        translation: "Sınıflandırma",
        example: "Image classification is a common AI task.",
        difficulty: "intermediate",
        partOfSpeech: "noun",
      },
      {
        id: "wt27",
        term: "Prompt",
        translation: "İstem",
        example: "Write a clear prompt for the AI model.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "wt28",
        term: "Inference",
        translation: "Çıkarım",
        example: "Model inference takes only milliseconds.",
        difficulty: "advanced",
        partOfSpeech: "noun",
      },
      {
        id: "wt29",
        term: "Epoch",
        translation: "Dönem",
        example: "We trained the model for 100 epochs.",
        difficulty: "advanced",
        partOfSpeech: "noun",
      },
      {
        id: "wt30",
        term: "Fine-tuning",
        translation: "İnce ayar",
        example: "Fine-tuning improved model performance significantly.",
        difficulty: "advanced",
        partOfSpeech: "noun",
      },
    ],
  },
  {
    id: "pre-tr-daily-shopping",
    name: "Alışveriş",
    topic: "Alışveriş & Mağaza",
    topicCategory: "daily_life",
    description: "Alışveriş yaparken kullanılan İngilizce kelimeler.",
    listLanguage: "Turkish",
    words: [
      {
        id: "wt31",
        term: "Receipt",
        translation: "Fiş",
        example: "Please keep your receipt for returns.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "wt32",
        term: "Discount",
        translation: "İndirim",
        example: "There is a 20% discount on all items.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "wt33",
        term: "Refund",
        translation: "İade",
        example: "I would like to request a refund.",
        difficulty: "intermediate",
        partOfSpeech: "noun",
      },
      {
        id: "wt34",
        term: "Cashier",
        translation: "Kasiyer",
        example: "Please pay at the cashier.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "wt35",
        term: "Bargain",
        translation: "Pazarlık",
        example: "I found a great bargain at the market.",
        difficulty: "intermediate",
        partOfSpeech: "noun",
      },
      {
        id: "wt36",
        term: "Aisle",
        translation: "Koridor",
        example: "You can find bread in aisle 5.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "wt37",
        term: "Cart",
        translation: "Alışveriş arabası",
        example: "I need a cart for my groceries.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "wt38",
        term: "Warranty",
        translation: "Garanti",
        example: "This product comes with a 2-year warranty.",
        difficulty: "intermediate",
        partOfSpeech: "noun",
      },
      {
        id: "wt39",
        term: "Out of stock",
        translation: "Stokta yok",
        example: "Sorry, that item is out of stock.",
        difficulty: "beginner",
        partOfSpeech: "adjective",
      },
      {
        id: "wt40",
        term: "Exchange",
        translation: "Değişim",
        example: "Can I exchange this for a larger size?",
        difficulty: "intermediate",
        partOfSpeech: "verb",
      },
    ],
  },
  {
    id: "pre-tr-academic-exam",
    name: "Sınav Hazırlık",
    topic: "Sınav & Akademik",
    topicCategory: "academic",
    description: "Akademik sınavlara hazırlıkta karşılaşılan kelimeler.",
    listLanguage: "Turkish",
    words: [
      {
        id: "wt41",
        term: "Syllabus",
        translation: "Müfredat",
        example: "Check the syllabus for exam dates.",
        difficulty: "intermediate",
        partOfSpeech: "noun",
      },
      {
        id: "wt42",
        term: "Curriculum",
        translation: "Öğretim programı",
        example: "The curriculum was updated this year.",
        difficulty: "intermediate",
        partOfSpeech: "noun",
      },
      {
        id: "wt43",
        term: "Prerequisite",
        translation: "Ön koşul",
        example: "Math 101 is a prerequisite for this course.",
        difficulty: "advanced",
        partOfSpeech: "noun",
      },
      {
        id: "wt44",
        term: "Semester",
        translation: "Dönem",
        example: "The fall semester starts in September.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "wt45",
        term: "Enrollment",
        translation: "Kayıt",
        example: "Enrollment for next semester is now open.",
        difficulty: "intermediate",
        partOfSpeech: "noun",
      },
      {
        id: "wt46",
        term: "Scholarship",
        translation: "Burs",
        example: "She received a full scholarship.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "wt47",
        term: "Lecture",
        translation: "Ders",
        example: "The lecture starts at 9 AM.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "wt48",
        term: "Assignment",
        translation: "Ödev",
        example: "The assignment is due next Monday.",
        difficulty: "beginner",
        partOfSpeech: "noun",
      },
      {
        id: "wt49",
        term: "GPA",
        translation: "Not ortalaması",
        example: "You need a minimum GPA of 3.0 to graduate.",
        difficulty: "intermediate",
        partOfSpeech: "noun",
      },
      {
        id: "wt50",
        term: "Elective",
        translation: "Seçmeli ders",
        example: "I chose photography as my elective.",
        difficulty: "intermediate",
        partOfSpeech: "noun",
      },
    ],
  },
];

export function getPredefinedListsByLocale(
  locale: "en" | "tr",
): PredefinedList[] {
  return locale === "tr" ? PREDEFINED_LISTS_TR : PREDEFINED_LISTS_EN;
}
